name = "pingpongtech-blog"
compatibility_date = "2024-06-01"

[pages_build_config]
  build_command = "hugo --minify"
  destination = "public"

[build]
  command = "hugo --minify"
  output_dir = "public"

[env]
  HUGO_VERSION = "0.126.0"
